# Generated by Django 2.2 on 2019-04-09 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('nomina', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('nomina', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PEND', 'Pendiente'), ('PROG', 'En Profreso'), ('RESG', 'Reasignado'), ('TERM', 'Terminado')], default='PEND', max_length=5)),
                ('request_type', models.CharField(choices=[('TECNO', 'Asesoría Tecnológica'), ('PLAT', 'Asesoría de Plataforma'), ('PEDAG', 'Asesoría Pedagógica'), ('CAPA', 'Asesoría de Capacitación'), ('CADIS', 'Solicitudes de CADIS'), ('COPIA', 'Copia de Plataforma'), ('ESPA', 'Espacio de Plataforma'), ('CUEN', 'Cuenta de Plataforma'), ('ENRL', 'Enrolamiento de Plataforma')], default='PLAT', max_length=5)),
                ('advice_type', models.CharField(choices=[('EMA', 'Solicitud por Email'), ('TEL', 'Solicitud por Teléfono'), ('PRES', 'Solicitud Presencial'), ('ONL', 'En Línea')], default='PRES', max_length=5)),
                ('platform_type', models.CharField(choices=[('BLACK', 'Blackboard'), ('CANV', 'Canvas'), ('OTHER', 'Otra')], default='BLACK', max_length=5)),
                ('description', models.TextField()),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_id', models.CharField(blank=True, max_length=10, null=True)),
                ('reassigned_ticket', models.CharField(blank=True, max_length=20, null=True)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', related_query_name='request', to='ceddiesk_app.Adviser')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', related_query_name='request', to='ceddiesk_app.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='ceddiesk_app.Request')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', related_query_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
